services:
  mysql:
    image: mysql:8.0
    container_name: kuit-hackathon-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kuit_hackathon
      MYSQL_ROOT_PASSWORD: root1234
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
